"""
fleet_data.py — Synthetic multi-cloud server telemetry
Covers every Agent 1 rule path at least twice, plus healthy servers for contrast.
All fields from the frozen schema in Section 3B are present on every server.
"""

FLEET = [
    # ─────────────────────────────────────────────────────────────
    # OVERPROVISIONED (3-4): p95_cpu < 15%, p95_ram/total < 35%
    # ─────────────────────────────────────────────────────────────
    {
        "server_id": "AWS-WEB-001",
        "provider": "AWS",
        "instance_type": "m6i.2xlarge",
        "environment": "production",
        "workload_type": "web_api",
        "vcpus": 8,
        "total_ram_gb": 32.0,
        "hourly_cost_usd": 0.3840,
        "p95_cpu_percent": 6.2,
        "p95_ram_used_gb": 9.5,
        "peak_ram_used_gb": 11.2,
        "peak_vcpus_used": 1.4,
        "gpu_util_percent": 0.0,
        "gpu_idle_hours": 0.0,
        "runtime_hours_per_week": 168,
        "network_in_out_mb_day": 820.0,
    },
    {
        "server_id": "AZURE-WEB-002",
        "provider": "AZURE",
        "instance_type": "Standard_D8s_v5",
        "environment": "production",
        "workload_type": "web_api",
        "vcpus": 8,
        "total_ram_gb": 32.0,
        "hourly_cost_usd": 0.3840,
        "p95_cpu_percent": 8.1,
        "p95_ram_used_gb": 8.0,
        "peak_ram_used_gb": 10.1,
        "peak_vcpus_used": 1.6,
        "gpu_util_percent": 0.0,
        "gpu_idle_hours": 0.0,
        "runtime_hours_per_week": 168,
        "network_in_out_mb_day": 540.0,
    },
    {
        "server_id": "AWS-BATCH-003",
        "provider": "AWS",
        "instance_type": "m6i.xlarge",
        "environment": "staging",
        "workload_type": "batch",
        "vcpus": 4,
        "total_ram_gb": 16.0,
        "hourly_cost_usd": 0.1920,
        "p95_cpu_percent": 7.4,
        "p95_ram_used_gb": 3.8,
        "peak_ram_used_gb": 4.5,
        "peak_vcpus_used": 0.9,
        "gpu_util_percent": 0.0,
        "gpu_idle_hours": 0.0,
        "runtime_hours_per_week": 168,
        "network_in_out_mb_day": 210.0,
    },
    {
        "server_id": "AZURE-BATCH-004",
        "provider": "AZURE",
        "instance_type": "Standard_D4s_v5",
        "environment": "dev",
        "workload_type": "batch",
        "vcpus": 4,
        "total_ram_gb": 16.0,
        "hourly_cost_usd": 0.1920,
        "p95_cpu_percent": 5.0,
        "p95_ram_used_gb": 2.9,
        "peak_ram_used_gb": 3.5,
        "peak_vcpus_used": 0.7,
        "gpu_util_percent": 0.0,
        "gpu_idle_hours": 0.0,
        "runtime_hours_per_week": 168,
        "network_in_out_mb_day": 155.0,
    },

    # ─────────────────────────────────────────────────────────────
    # ZOMBIE GPU (2-3): ai_inference, gpu_util < 2%, gpu_idle_hours >= 6
    # ─────────────────────────────────────────────────────────────
    {
        "server_id": "AWS-GPU-005",
        "provider": "AWS",
        "instance_type": "g5.2xlarge",
        "environment": "production",
        "workload_type": "ai_inference",
        "vcpus": 8,
        "total_ram_gb": 32.0,
        "hourly_cost_usd": 1.2120,
        "p95_cpu_percent": 4.0,
        "p95_ram_used_gb": 6.0,
        "peak_ram_used_gb": 8.0,
        "peak_vcpus_used": 1.0,
        "gpu_util_percent": 0.8,
        "gpu_idle_hours": 18.0,
        "runtime_hours_per_week": 168,
        "network_in_out_mb_day": 320.0,
    },
    {
        "server_id": "AZURE-GPU-006",
        "provider": "AZURE",
        "instance_type": "Standard_NC6s_v3",
        "environment": "staging",
        "workload_type": "ai_inference",
        "vcpus": 6,
        "total_ram_gb": 112.0,
        "hourly_cost_usd": 1.1420,
        "p95_cpu_percent": 3.5,
        "p95_ram_used_gb": 10.0,
        "peak_ram_used_gb": 14.0,
        "peak_vcpus_used": 1.2,
        "gpu_util_percent": 1.1,
        "gpu_idle_hours": 12.0,
        "runtime_hours_per_week": 168,
        "network_in_out_mb_day": 190.0,
    },
    {
        "server_id": "AWS-GPU-007",
        "provider": "AWS",
        "instance_type": "g5.2xlarge",
        "environment": "dev",
        "workload_type": "ai_inference",
        "vcpus": 8,
        "total_ram_gb": 32.0,
        "hourly_cost_usd": 1.2120,
        "p95_cpu_percent": 2.0,
        "p95_ram_used_gb": 5.5,
        "peak_ram_used_gb": 7.0,
        "peak_vcpus_used": 0.8,
        "gpu_util_percent": 0.3,
        "gpu_idle_hours": 22.0,
        "runtime_hours_per_week": 168,
        "network_in_out_mb_day": 85.0,
    },

    # ─────────────────────────────────────────────────────────────
    # ZOMBIE IDLE (2-3): network_in_out_mb_day < 5
    # ─────────────────────────────────────────────────────────────
    {
        "server_id": "AWS-LEGACY-008",
        "provider": "AWS",
        "instance_type": "t3.large",
        "environment": "production",
        "workload_type": "web_api",
        "vcpus": 2,
        "total_ram_gb": 8.0,
        "hourly_cost_usd": 0.0832,
        "p95_cpu_percent": 1.2,
        "p95_ram_used_gb": 1.1,
        "peak_ram_used_gb": 1.4,
        "peak_vcpus_used": 0.1,
        "gpu_util_percent": 0.0,
        "gpu_idle_hours": 0.0,
        "runtime_hours_per_week": 168,
        "network_in_out_mb_day": 1.8,
    },
    {
        "server_id": "AZURE-LEGACY-009",
        "provider": "AZURE",
        "instance_type": "Standard_B2ms",
        "environment": "dev",
        "workload_type": "batch",
        "vcpus": 2,
        "total_ram_gb": 8.0,
        "hourly_cost_usd": 0.0832,
        "p95_cpu_percent": 0.8,
        "p95_ram_used_gb": 0.9,
        "peak_ram_used_gb": 1.2,
        "peak_vcpus_used": 0.1,
        "gpu_util_percent": 0.0,
        "gpu_idle_hours": 0.0,
        "runtime_hours_per_week": 168,
        "network_in_out_mb_day": 0.5,
    },
    {
        "server_id": "AWS-DECOM-010",
        "provider": "AWS",
        "instance_type": "t3.xlarge",
        "environment": "qa",
        "workload_type": "web_api",
        "vcpus": 4,
        "total_ram_gb": 16.0,
        "hourly_cost_usd": 0.1664,
        "p95_cpu_percent": 0.5,
        "p95_ram_used_gb": 0.7,
        "peak_ram_used_gb": 0.9,
        "peak_vcpus_used": 0.1,
        "gpu_util_percent": 0.0,
        "gpu_idle_hours": 0.0,
        "runtime_hours_per_week": 168,
        "network_in_out_mb_day": 2.1,
    },

    # ─────────────────────────────────────────────────────────────
    # UNSCHEDULED NON-PROD (3-4): dev/staging/qa, runtime == 168
    # ─────────────────────────────────────────────────────────────
    {
        "server_id": "AWS-DEV-011",
        "provider": "AWS",
        "instance_type": "t3.large",
        "environment": "dev",
        "workload_type": "web_api",
        "vcpus": 2,
        "total_ram_gb": 8.0,
        "hourly_cost_usd": 0.0832,
        "p95_cpu_percent": 22.0,
        "p95_ram_used_gb": 4.2,
        "peak_ram_used_gb": 5.1,
        "peak_vcpus_used": 0.7,
        "gpu_util_percent": 0.0,
        "gpu_idle_hours": 0.0,
        "runtime_hours_per_week": 168,
        "network_in_out_mb_day": 450.0,
    },
    {
        "server_id": "AZURE-STG-012",
        "provider": "AZURE",
        "instance_type": "Standard_D4s_v5",
        "environment": "staging",
        "workload_type": "database",
        "vcpus": 4,
        "total_ram_gb": 16.0,
        "hourly_cost_usd": 0.1920,
        "p95_cpu_percent": 28.0,
        "p95_ram_used_gb": 7.0,
        "peak_ram_used_gb": 8.5,
        "peak_vcpus_used": 1.5,
        "gpu_util_percent": 0.0,
        "gpu_idle_hours": 0.0,
        "runtime_hours_per_week": 168,
        "network_in_out_mb_day": 630.0,
    },
    {
        "server_id": "AWS-QA-013",
        "provider": "AWS",
        "instance_type": "m6i.large",
        "environment": "qa",
        "workload_type": "web_api",
        "vcpus": 2,
        "total_ram_gb": 8.0,
        "hourly_cost_usd": 0.0960,
        "p95_cpu_percent": 18.5,
        "p95_ram_used_gb": 3.5,
        "peak_ram_used_gb": 4.2,
        "peak_vcpus_used": 0.6,
        "gpu_util_percent": 0.0,
        "gpu_idle_hours": 0.0,
        "runtime_hours_per_week": 168,
        "network_in_out_mb_day": 310.0,
    },
    {
        "server_id": "AZURE-DEV-014",
        "provider": "AZURE",
        "instance_type": "Standard_B4ms",
        "environment": "dev",
        "workload_type": "batch",
        "vcpus": 4,
        "total_ram_gb": 16.0,
        "hourly_cost_usd": 0.1660,
        "p95_cpu_percent": 31.0,
        "p95_ram_used_gb": 5.8,
        "peak_ram_used_gb": 7.0,
        "peak_vcpus_used": 1.6,
        "gpu_util_percent": 0.0,
        "gpu_idle_hours": 0.0,
        "runtime_hours_per_week": 168,
        "network_in_out_mb_day": 280.0,
    },

    # ─────────────────────────────────────────────────────────────
    # HIGH-RISK PRODUCTION DATABASE — key demo moment
    # Should score REJECTED or APPROVED_WITH_CONDITIONS
    # ─────────────────────────────────────────────────────────────
    {
        "server_id": "AWS-DB-015",
        "provider": "AWS",
        "instance_type": "m6i.2xlarge",
        "environment": "production",
        "workload_type": "database",
        "vcpus": 8,
        "total_ram_gb": 32.0,
        "hourly_cost_usd": 0.3840,
        "p95_cpu_percent": 9.0,
        "p95_ram_used_gb": 8.0,
        "peak_ram_used_gb": 16.5,
        "peak_vcpus_used": 1.8,
        "gpu_util_percent": 0.0,
        "gpu_idle_hours": 0.0,
        "runtime_hours_per_week": 168,
        "network_in_out_mb_day": 1200.0,
    },

    # ─────────────────────────────────────────────────────────────
    # NO_SAFE_DOWNSIZE_AVAILABLE — low CPU but RAM spike so large that
    # every non-GPU Azure catalog tier is already exhausted.
    # peak_ram=28GB * 1.3 = 36.4GB target — larger than Standard_D8s_v5 (32GB),
    # so no eligible non-GPU tier fits; Agent 2 returns NO_SAFE_DOWNSIZE_AVAILABLE.
    # ─────────────────────────────────────────────────────────────
    {
        "server_id": "AZURE-MEM-016",
        "provider": "AZURE",
        "instance_type": "Standard_D8s_v5",
        "environment": "production",
        "workload_type": "web_api",
        "vcpus": 8,
        "total_ram_gb": 32.0,
        "hourly_cost_usd": 0.3840,
        "p95_cpu_percent": 7.0,
        "p95_ram_used_gb": 26.0,
        "peak_ram_used_gb": 28.0,
        "peak_vcpus_used": 1.2,
        "gpu_util_percent": 0.0,
        "gpu_idle_hours": 0.0,
        "runtime_hours_per_week": 168,
        "network_in_out_mb_day": 910.0,
    },

    # ─────────────────────────────────────────────────────────────
    # HEALTHY SERVERS (2-3): Should NOT be flagged by any rule
    # ─────────────────────────────────────────────────────────────
    {
        "server_id": "AWS-WEB-017",
        "provider": "AWS",
        "instance_type": "m6i.large",
        "environment": "production",
        "workload_type": "web_api",
        "vcpus": 2,
        "total_ram_gb": 8.0,
        "hourly_cost_usd": 0.0960,
        "p95_cpu_percent": 52.0,
        "p95_ram_used_gb": 5.5,
        "peak_ram_used_gb": 6.8,
        "peak_vcpus_used": 1.4,
        "gpu_util_percent": 0.0,
        "gpu_idle_hours": 0.0,
        "runtime_hours_per_week": 168,
        "network_in_out_mb_day": 2100.0,
    },
    {
        "server_id": "AZURE-DB-018",
        "provider": "AZURE",
        "instance_type": "Standard_D8s_v5",
        "environment": "production",
        "workload_type": "database",
        "vcpus": 8,
        "total_ram_gb": 32.0,
        "hourly_cost_usd": 0.3840,
        "p95_cpu_percent": 44.0,
        "p95_ram_used_gb": 18.0,
        "peak_ram_used_gb": 22.5,
        "peak_vcpus_used": 4.2,
        "gpu_util_percent": 0.0,
        "gpu_idle_hours": 0.0,
        "runtime_hours_per_week": 168,
        "network_in_out_mb_day": 5800.0,
    },
]


def get_fleet() -> list:
    """Return the full list of synthetic server telemetry dicts."""
    return FLEET
