"""
generate_fleet_history.py
==========================
Generates 14 days of hourly telemetry for the full 18-server fleet.

Populates data/history/*.csv and data/fleet_metadata.json.
No network calls. Pure local Python.

Usage:
    python generate_fleet_history.py
"""

import json
from datetime import datetime, timedelta
from pathlib import Path

import numpy as np
import pandas as pd

np.random.seed(42)

DATA_DIR = Path("data")
HISTORY_DIR = DATA_DIR / "history"
START = datetime(2026, 9, 1, 0, 0, 0)
DAYS = 14


def clip(x, lo=0, hi=100):
    return max(lo, min(hi, x))


def generate_timeseries(resource_id, hourly_fn, days=DAYS):
    records = []
    for h in range(days * 24):
        ts = START + timedelta(hours=h)
        day_idx = h // 24
        hour_of_day = h % 24
        weekday = ts.weekday()
        cpu, mem, gpu, net, req, lat, err = hourly_fn(day_idx, hour_of_day, weekday)
        records.append({
            "resource_id": resource_id,
            "timestamp": ts.isoformat() + "Z",
            "day_index": day_idx,
            "hour_of_day": hour_of_day,
            "weekday": weekday,
            "cpu_percent": round(clip(cpu), 2),
            "memory_percent": round(clip(mem), 2),
            "gpu_percent": round(clip(gpu), 2),
            "network_mb": round(max(0, net), 1),
            "request_count": max(0, int(req)),
            "latency_ms": round(max(0, lat), 1),
            "error_rate_percent": round(clip(err, 0, 100), 3),
            "running": True,
        })
    return pd.DataFrame(records)


# ---- 4 hand-tuned STORY servers ----

def gpu_001_story(day_idx, hour_of_day, weekday):
    is_training_window = 18 <= hour_of_day <= 22
    if is_training_window:
        cpu = 68 + np.random.normal(0, 6)
        gpu = 94 + np.random.normal(0, 3)
        mem = 78 + np.random.normal(0, 4)
        net = 3800 + np.random.normal(0, 300)
    else:
        cpu = 8 + np.random.normal(0, 2)
        gpu = 3 + np.random.normal(0, 1.5)
        mem = 22 + np.random.normal(0, 3)
        net = 150 + np.random.normal(0, 40)
    return cpu, mem, gpu, net, 0, 0, 0


def ec2_001_story(day_idx, hour_of_day, weekday):
    is_weekday = weekday < 5
    is_business_hours = 8 <= hour_of_day <= 18
    if is_weekday and is_business_hours:
        cpu = 42 + np.random.normal(0, 8)
        mem = 55 + np.random.normal(0, 6)
        req = 200 + np.random.normal(0, 40)
        net = 900 + np.random.normal(0, 150)
        lat = 60 + np.random.normal(0, 8)
    else:
        cpu = 2 + np.random.normal(0, 1)
        mem = 9 + np.random.normal(0, 2)
        req = 0
        net = 5 + np.random.normal(0, 2)
        lat = 0
    return cpu, mem, 0, net, req, lat, 0.1


def db_prod_001_story(day_idx, hour_of_day, weekday):
    is_business_hours = 8 <= hour_of_day <= 20
    baseline = 62 if is_business_hours else 48
    cpu = baseline + np.random.normal(0, 5)
    mem = baseline + 15 + np.random.normal(0, 4)
    req = 150000 + np.random.normal(0, 15000)
    net = 6000 + np.random.normal(0, 500)
    lat = 15 + np.random.normal(0, 3)
    return cpu, mem, 0, net, req, lat, 0.15


def api_prod_001_story(day_idx, hour_of_day, weekday):
    is_business_hours = 7 <= hour_of_day <= 22
    is_spike_day = day_idx == 9
    is_spike_window = is_spike_day and 10 <= hour_of_day <= 14
    if is_spike_window:
        cpu = 91 + np.random.normal(0, 4)
        mem = 88 + np.random.normal(0, 3)
        req = 400000 + np.random.normal(0, 20000)
        lat = 220 + np.random.normal(0, 20)
        err = 2.5 + np.random.normal(0, 0.5)
        net = 18000 + np.random.normal(0, 1000)
    elif is_business_hours:
        cpu = 38 + np.random.normal(0, 6)
        mem = 50 + np.random.normal(0, 5)
        req = 170000 + np.random.normal(0, 15000)
        lat = 90 + np.random.normal(0, 10)
        err = 0.3 + np.random.normal(0, 0.1)
        net = 7500 + np.random.normal(0, 600)
    else:
        cpu = 14 + np.random.normal(0, 3)
        mem = 30 + np.random.normal(0, 4)
        req = 40000 + np.random.normal(0, 5000)
        lat = 45 + np.random.normal(0, 5)
        err = 0.1
        net = 2000 + np.random.normal(0, 300)
    return cpu, mem, 0, net, req, lat, err


STORY_SERVERS = {
    "gpu-001": gpu_001_story,
    "ec2-001": ec2_001_story,
    "db-prod-001": db_prod_001_story,
    "api-prod-001": api_prod_001_story,
}


# ---- Remaining fleet: randomly generated by waste profile ----

REMAINING_SPECS = [
    {"resource_id": "ec2-002", "profile": "idle_dev", "base_cpu": 4, "base_mem": 12, "gpu": False},
    {"resource_id": "ec2-003", "profile": "idle_qa", "base_cpu": 3, "base_mem": 10, "gpu": False},
    {"resource_id": "ec2-004", "profile": "overprovisioned", "base_cpu": 12, "base_mem": 18, "gpu": False},
    {"resource_id": "gpu-002", "profile": "zombie_gpu", "base_cpu": 6, "base_mem": 15, "gpu": True},
    {"resource_id": "ec2-005", "profile": "staging_247", "base_cpu": 9, "base_mem": 20, "gpu": False},
    {"resource_id": "api-prod-002", "profile": "steady_prod", "base_cpu": 48, "base_mem": 58, "gpu": False},
    {"resource_id": "db-prod-002", "profile": "steady_prod", "base_cpu": 52, "base_mem": 65, "gpu": False},
    {"resource_id": "ec2-006", "profile": "batch_job", "base_cpu": 10, "base_mem": 22, "gpu": False},
    {"resource_id": "ec2-007", "profile": "overprovisioned", "base_cpu": 15, "base_mem": 24, "gpu": False},
    {"resource_id": "storage-001", "profile": "orphaned_storage", "base_cpu": 0, "base_mem": 0, "gpu": False},
    {"resource_id": "ec2-008", "profile": "idle_dev", "base_cpu": 5, "base_mem": 14, "gpu": False},
    {"resource_id": "api-prod-003", "profile": "steady_prod", "base_cpu": 44, "base_mem": 55, "gpu": False},
    {"resource_id": "ec2-009", "profile": "unscheduled_nonprod", "base_cpu": 7, "base_mem": 16, "gpu": False},
    {"resource_id": "gpu-003", "profile": "zombie_gpu", "base_cpu": 8, "base_mem": 18, "gpu": True},
]


def make_random_profile(base_cpu, base_mem, has_gpu, profile):
    def fn(day_idx, hour_of_day, weekday):
        noise_c = np.random.normal(0, 3)
        noise_m = np.random.normal(0, 3)

        if profile == "orphaned_storage":
            return 0, 0, 0, 0, 0, 0, 0

        if profile == "batch_job" and hour_of_day in (2, 3, 4):
            cpu = 55 + np.random.normal(0, 8)
            mem = 60 + np.random.normal(0, 6)
        elif profile == "unscheduled_nonprod":
            cpu = base_cpu + noise_c + (5 if 9 <= hour_of_day <= 17 else 0)
            mem = base_mem + noise_m
        else:
            cpu = base_cpu + noise_c
            mem = base_mem + noise_m

        gpu = (4 + np.random.normal(0, 1.5)) if has_gpu else 0
        net = 100 + np.random.normal(0, 30)
        req = 50 + np.random.normal(0, 15) if base_cpu > 20 else 0
        lat = 30 + np.random.normal(0, 5) if base_cpu > 20 else 0
        err = 0.1
        return cpu, mem, gpu, net, req, lat, err
    return fn


FLEET_METADATA = [
    {"resource_id": "gpu-001", "instance_type": "g5.xlarge", "provider": "aws", "vcpu": 4, "memory_gb": 16, "has_gpu": True, "environment": "production", "workload_type": "ml-training", "hourly_cost_usd": 1.20, "criticality": "high"},
    {"resource_id": "ec2-001", "instance_type": "m5.2xlarge", "provider": "aws", "vcpu": 8, "memory_gb": 32, "has_gpu": False, "environment": "development", "workload_type": "web-dev", "hourly_cost_usd": 0.38, "criticality": "low"},
    {"resource_id": "db-prod-001", "instance_type": "db.r6g.xlarge", "provider": "aws", "vcpu": 4, "memory_gb": 32, "has_gpu": False, "environment": "production", "workload_type": "database", "hourly_cost_usd": 0.50, "criticality": "critical"},
    {"resource_id": "api-prod-001", "instance_type": "m5.large", "provider": "aws", "vcpu": 2, "memory_gb": 8, "has_gpu": False, "environment": "production", "workload_type": "api-gateway", "hourly_cost_usd": 0.096, "criticality": "high"},
    {"resource_id": "ec2-002", "instance_type": "m5.xlarge", "provider": "aws", "vcpu": 4, "memory_gb": 16, "has_gpu": False, "environment": "development", "workload_type": "internal-tool", "hourly_cost_usd": 0.192, "criticality": "low"},
    {"resource_id": "ec2-003", "instance_type": "m5.large", "provider": "aws", "vcpu": 2, "memory_gb": 8, "has_gpu": False, "environment": "qa", "workload_type": "test-runner", "hourly_cost_usd": 0.096, "criticality": "low"},
    {"resource_id": "ec2-004", "instance_type": "m5.2xlarge", "provider": "azure", "vcpu": 8, "memory_gb": 32, "has_gpu": False, "environment": "production", "workload_type": "batch-job", "hourly_cost_usd": 0.384, "criticality": "medium"},
    {"resource_id": "gpu-002", "instance_type": "Standard_NC6", "provider": "azure", "vcpu": 6, "memory_gb": 56, "has_gpu": True, "environment": "staging", "workload_type": "ml-inference", "hourly_cost_usd": 0.90, "criticality": "medium"},
    {"resource_id": "ec2-005", "instance_type": "Standard_D4s_v3", "provider": "azure", "vcpu": 4, "memory_gb": 16, "has_gpu": False, "environment": "staging", "workload_type": "internal-tool", "hourly_cost_usd": 0.192, "criticality": "low"},
    {"resource_id": "api-prod-002", "instance_type": "m5.xlarge", "provider": "aws", "vcpu": 4, "memory_gb": 16, "has_gpu": False, "environment": "production", "workload_type": "api-gateway", "hourly_cost_usd": 0.192, "criticality": "high"},
    {"resource_id": "db-prod-002", "instance_type": "Standard_D8s_v3", "provider": "azure", "vcpu": 8, "memory_gb": 32, "has_gpu": False, "environment": "production", "workload_type": "database", "hourly_cost_usd": 0.384, "criticality": "critical"},
    {"resource_id": "ec2-006", "instance_type": "m5.large", "provider": "aws", "vcpu": 2, "memory_gb": 8, "has_gpu": False, "environment": "production", "workload_type": "batch-job", "hourly_cost_usd": 0.096, "criticality": "medium"},
    {"resource_id": "ec2-007", "instance_type": "m5.2xlarge", "provider": "aws", "vcpu": 8, "memory_gb": 32, "has_gpu": False, "environment": "staging", "workload_type": "internal-tool", "hourly_cost_usd": 0.384, "criticality": "low"},
    {"resource_id": "storage-001", "instance_type": "gp3-500gb", "provider": "aws", "vcpu": 0, "memory_gb": 0, "has_gpu": False, "environment": "production", "workload_type": "orphaned-volume", "hourly_cost_usd": 0.055, "criticality": "low"},
    {"resource_id": "ec2-008", "instance_type": "m5.xlarge", "provider": "aws", "vcpu": 4, "memory_gb": 16, "has_gpu": False, "environment": "development", "workload_type": "web-dev", "hourly_cost_usd": 0.192, "criticality": "low"},
    {"resource_id": "api-prod-003", "instance_type": "Standard_D4s_v3", "provider": "azure", "vcpu": 4, "memory_gb": 16, "has_gpu": False, "environment": "production", "workload_type": "api-gateway", "hourly_cost_usd": 0.192, "criticality": "high"},
    {"resource_id": "ec2-009", "instance_type": "m5.xlarge", "provider": "aws", "vcpu": 4, "memory_gb": 16, "has_gpu": False, "environment": "qa", "workload_type": "test-runner", "hourly_cost_usd": 0.192, "criticality": "low"},
    {"resource_id": "gpu-003", "instance_type": "g5.xlarge", "provider": "aws", "vcpu": 4, "memory_gb": 16, "has_gpu": True, "environment": "staging", "workload_type": "ml-inference", "hourly_cost_usd": 1.20, "criticality": "medium"},
]

# Mapping between fleet_data server IDs and user's story IDs
ID_MAP = {
    "ec2-001": "AWS-WEB-001",
    "ec2-004": "AZURE-WEB-002",
    "ec2-002": "AWS-BATCH-003",
    "ec2-005": "AZURE-BATCH-004",
    "gpu-001": "AWS-GPU-005",
    "gpu-002": "AZURE-GPU-006",
    "gpu-003": "AWS-GPU-007",
    "ec2-007": "AWS-LEGACY-008",
    "ec2-009": "AZURE-LEGACY-009",
    "ec2-006": "AWS-DECOM-010",
    "api-prod-002": "AWS-DEV-011",
    "api-prod-003": "AZURE-STG-012",
    "ec2-003": "AWS-QA-013",
    "ec2-008": "AZURE-DEV-014",
    "db-prod-001": "AWS-DB-015",
    "storage-001": "AZURE-MEM-016",
    "api-prod-001": "AWS-WEB-017",
    "db-prod-002": "AZURE-DB-018",
}


def main():
    HISTORY_DIR.mkdir(parents=True, exist_ok=True)

    metadata_dict = {item["resource_id"]: item for item in FLEET_METADATA}

    for resource_id, fn in STORY_SERVERS.items():
        df = generate_timeseries(resource_id, fn)
        df.to_csv(HISTORY_DIR / f"{resource_id}_history.csv", index=False)

        # Also write mapped fleet ID
        mapped_id = ID_MAP.get(resource_id)
        if mapped_id:
            df_mapped = df.copy()
            df_mapped["resource_id"] = mapped_id
            df_mapped.to_csv(HISTORY_DIR / f"{mapped_id}_history.csv", index=False)
            mapped_meta = dict(metadata_dict[resource_id])
            mapped_meta["resource_id"] = mapped_id
            metadata_dict[mapped_id] = mapped_meta

        print(f"[story]  {resource_id:15s} avg_cpu={df.cpu_percent.mean():5.1f}%  "
              f"p95={df.cpu_percent.quantile(0.95):5.1f}%  max={df.cpu_percent.max():5.1f}%")

    for spec in REMAINING_SPECS:
        fn = make_random_profile(spec["base_cpu"], spec["base_mem"], spec["gpu"], spec["profile"])
        df = generate_timeseries(spec["resource_id"], fn)
        df.to_csv(HISTORY_DIR / f"{spec['resource_id']}_history.csv", index=False)

        mapped_id = ID_MAP.get(spec["resource_id"])
        if mapped_id:
            df_mapped = df.copy()
            df_mapped["resource_id"] = mapped_id
            df_mapped.to_csv(HISTORY_DIR / f"{mapped_id}_history.csv", index=False)
            mapped_meta = dict(metadata_dict[spec["resource_id"]])
            mapped_meta["resource_id"] = mapped_id
            metadata_dict[mapped_id] = mapped_meta

        print(f"[random] {spec['resource_id']:15s} avg_cpu={df.cpu_percent.mean():5.1f}%  "
              f"p95={df.cpu_percent.quantile(0.95):5.1f}%  profile={spec['profile']}")

    with open(DATA_DIR / "fleet_metadata.json", "w", encoding="utf-8") as f:
        json.dump(list(metadata_dict.values()), f, indent=2)

    print(f"\nDone. Generated history for all servers.")
    print(f"Metadata written to {DATA_DIR / 'fleet_metadata.json'}")


if __name__ == "__main__":
    main()
